### ISSUE TITLE
Common names

### ISSUE THREAD

**Issue by mitztastic** [BananaPuncher714/LethalQuantities#14]
I'm guessing the names used are the game's internal monster code names, however it's quite inconvenient for a modder to have to guess or go in and test every spawn--is there any chance you can atleast add the official aliases in the mod e,g, Crawler -> aka Thumper
This would make things more user-friendly imho.

**Comment by Simmmmms** [comment]
This is a good idea, these will added in the future.

**Comment by BananaPuncher714** [comment]
It is currently a bit difficult to use the player friendly names, since they don't get loaded until the player is in the ship, at which point it is a bit too late to capture the default config values to save. For now, here is a dictionary for each vanilla enemy type:

- BaboonHawk -> Baboon Hawk
- Blob -> Hygrodere
- Centipede -> Snare Flea
- Crawler -> Thumper
- DocileLocustBees, RedLocustBees -> Roaming Locusts
- DoubleWing -> Manticoil
- DressGirl -> Ghost Girl
- Flowerman -> Bracken
- ForestGiant -> Forest Keeper
- HoarderBug -> Hoarding Bug
- Jester -> Jester
- LassoMan -> Lasso Man
- MaskedEnemyPlayer -> Masked
- MouthDog -> Eyeless Dog
- Nutcracker -> Nutcracker
- Puffer -> Spore LIzard
- SandSpider -> Bunker Spider
- SandWorm -> Earth Leviathan
- SpringMan -> Coil-Head

Hopefully it is not too inconvenient to memorize each enemy type.
