### ISSUE TITLE
Custom moons stuck on "waiting for crew" on second game of session

### ISSUE THREAD

**Issue by brokymeister** [BananaPuncher714/LethalQuantities#18]
Currently using multiple custom moon AND custom scrap mods. Since custom scrap does not spawn on custom moons by default, I wanted to use this mod to solve that. Whenever I open the game for the first time and host a file, it takes a really long time to load in, which I assume is the config files loading or something. All custom moons generate as expected with custom scrap. If I leave the file and start another one, it will load nearly instantly, but all custom moons will be stuck on "waiting for crew" when I try to load them (vanilla moons work fine). If I completely restart the game and start a new file, it will load for a long time again and custom moons will load normally, until I leave the file and start another one, which sticks me on "waiting for crew".

**Comment by BananaPuncher714** [comment]
Can you provide a list of mods you are using, or a profile code? Also, are there any errors in the console? The long load times are indeed caused by the BepInEx configuration API binding each option for each config, and it is shorter the second time around because the mod only attempts to load the config files once, to save time. I don't know why custom moons but not the vanilla moons would be affected though.

**Comment by brokymeister** [comment]
Here is a test profile I used: 018cb35d-700e-f5b2-fe8a-669be8dae195
After testing a bit more and only using LethalQuantities and a custom moon mod, the problem still seems to persist. If I disable LethalQuantities and run the profile, everything works perfectly. I have not touched any of the config files for the custom moon since their creation.
