### ISSUE TITLE
Scrap config page not working

### ISSUE THREAD

**Issue by brokymeister** [BananaPuncher714/LethalQuantities#19]
Hate to bother you but upon using the same test profile (018cb35d-700e-f5b2-fe8a-669be8dae195), the moons now load fine, but the game does not seem to read the scrap config files at all. I have change item rarities and min/max scrap amounts for both vanilla and custom moons, but none of the moons seem to reflect those changes at all. Console does not show any errors.

**Comment by BananaPuncher714** [comment]
Ok, thanks. I'll test it out, although I don't think anything should have changed.

**Comment by BananaPuncher714** [comment]
Did you forget to enable the scrap config for the moons you're trying to edit? Here are my scrap config values:
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/bd8cb6e0-103f-4f0d-86b8-d4fca90dfa1f)
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/3f046001-e7b6-4f29-8e76-fcb8184d51a5)
And here are the results using the [DetailedScan](https://thunderstore.io/c/lethal-company/p/fivetoofive/DetailedScan/) mod
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/ae8b669a-ed45-40c9-9ba1-1b82e4c16cd9)
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/0b4bb6c8-ac07-477b-b9ee-f2fc12d88c3e)
I set the rarity of the 7Ball extremely high so that it's almost guaranteed to be the only scrap item to spawn.

**Comment by brokymeister** [comment]
You're right, that's my bad
