### ISSUE TITLE
[Question] Is there a way to increase how frequently enemies spawn?

### ISSUE THREAD

**Issue by elliott-w** [BananaPuncher714/LethalQuantities#21]
I think it's default set to 2 hour cycle, but I'm trying to make a minimum number of enemies be spawned when you first enter the building.

Something like:
```
SpawnAmountCurve = 0:5, 1:15
```
Doesn't really seem to increase spawns that much.

**Comment by BananaPuncher714** [comment]
Unfortunately, the SpawnAmountRange is not an animation curve, so manipulating the amount that spawns at a certain time is still a little difficult. There is also currently no option in the configs to set the HourTimeBetweenEnemySpawnBatches either, so I don't really think it is possible to set the amount of enemies that already exist when the ship lands. You _can_ always manipulate the curve so that it is extremely high, like 0:100, then have it drop down to -3 or the default value at time 0.05. This will let you spawn a large amount of enemies over the first 2 hours of each day, which should range from 6 to 8.

**Comment by BananaPuncher714** [comment]
Closing this issue unless you have more questions. If spawning enemies before landing is a vanilla feature, then I'll add configuration options for it.
