### ISSUE TITLE
[QUESTION] I'm new to modding. I don't get where I write all of this.

### ISSUE THREAD

**Issue by Brackener** [BananaPuncher714/LethalQuantities#23]
Where do I type all of these commands?? The MinScrapCount and stuff like that. Could someone help me?

**Comment by Simmmmms** [comment]
Are you using r2modman and thunderstore? After you add the mod to your profile on r2modman you should be able to go to the config editor 
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/3964283/c551c931-d6b4-4666-814f-751e02639ee4)
and edit those values. You need to enter a game once with the mod installed in order to have the configs generate.

**Comment by Simmmmms** [comment]
Closing this ticket, if you have any more questions please open another.
