### ISSUE TITLE
AdvancedCompany incompatibility/Scrap values incorrect

### ISSUE THREAD

**Issue by jeffthepuppet** [BananaPuncher714/LethalQuantities#41]
I've found that enabling the scrap config for a planet means that any scrap spawned will share the same value with that same piece of scrap found elsewhere. Also, the scrap value modifier for the total scrap value doesn't seem to do anything anymore.

I also think there's a few compatibility issues with the newest version of AdvancedCompany. It appears to override any changes made by this mod.

**Comment by jeffthepuppet** [comment]
AdvancedCompany's new features are meant to configure enemy spawns and scrap. While I would go to them to ask to make this function something I can disable, I can't find any way to directly speak to them at this time. I like the extra control this mod offers over spawn curves, individual enemy rates, etc, so I really don't want to have to use their method.

**Comment by jeffthepuppet** [comment]
I'm really sorry to bother you with all of this, but now I'm finding a whole other issue where the dungeon gen config just isn't doing anything at all. I don't even know what's causing it, I'll do a little bit of experimenting, but I just don't know.

**Comment by BananaPuncher714** [comment]
What mods do you have, and what part of the dungeon gen config isn't working? What dungeon gen config are you trying to change, and what does your config look like? This was an incompatibility with LethalLevelLoader, but that should have been solved.

**Comment by jeffthepuppet** [comment]
From what I can tell, every part of the config isn't working, including the part that handles dungeon size. The specific thing I was doing was trying to put the MoreInteriors bunker map on Orion with a lower chance of having a mansion interior.

**Comment by BananaPuncher714** [comment]
Ok, I'll take a look. I don't think I can do anything about AdvancedCompany though, but you might be able to contact them in the Lethal Company modding discord.

**Comment by jeffthepuppet** [comment]
I looked further into it, definitely an issue with either MoreInteriors or modded interiors. Also, I checked the discord, they don't have anywhere to talk to the AdvancedCompany team, strangely. I keep looking but I genuinely think they just don't have anywhere to report stuff, which I find super odd.

**Comment by BananaPuncher714** [comment]
It seems like AdvancedCompany has a section under their mod-releases channel. As for the interiors, I am not sure how MoreInteriors does it, but I tested it with Scoopy's castle interior, and it seemed to work fine.

**Comment by jeffthepuppet** [comment]
I think I'll just use the MoreInteriors config to make any moons I want the bunker on to have a guaranteed spawn. Sorry for all the extra hassle. I've looked under the mod-releases channel and still don't see anything when I search for AdvancedCompany. 

This modpack thing is proving to be way more work than I was anticipating, lol. I appreciate the work you've done to help.

**Comment by BananaPuncher714** [comment]
I can try to do a little testing, but I'm not able to guarantee anything. It may have to stay incompatible if AdvancedCompany doesn't set their priority correctly or doesn't add an option to disable certain configs.

**Comment by jeffthepuppet** [comment]
I'll do some more tests, but new updates today might mean that AdvancedCompany is compatible again. I was able to get some baboon hawks spawning inside, but I'm not sure if that's just because AdvancedCompany doesn't list things when they're set to 0.

**Comment by BananaPuncher714** [comment]
The dungeon generation for any custom dungeon flows needs to be done by modifying the config for each mod, since it seems like LethalLevelLoader overrides any custom dungeon flow rarities that are set by LethalQuantities. Vanilla flows should still be modifiable, however.

As for the AdvancedCompany incompatibility, I'm not sure what issue you're encountering, since I generated scrap according to the config just fine. If the moon doesn't load, there should be some error in the console that should provide more information.

**Comment by BananaPuncher714** [comment]
Going to close this issue since it seems like most options in AdvancedCompany are disabled unless you enable the checkbox for each setting. I can't replicate any other issues that might occur with AdvancedCompany. The custom dungeon flow rarity not working is a separate problem due to LethalLevelLoader. If you have more information regarding this, feel free to re-open a ticket, or if it is a different problem, please open a new issue.
