### ISSUE TITLE
Outside enemies spawning inside

### ISSUE THREAD

**Issue by McAwesome123** [BananaPuncher714/LethalQuantities#44]
Recently, when using this mod, I've noticed that the game spawns Earth Leviathans inside the facility.

Since the mod list I was using was quite expansive, I wasn't sure if it was this mod specifically or something else interfering, but after putting together a mod list of just this mod, lethal days, and better saves, it still happened. r2modman profile code: 018d5252-97bb-43a6-bae6-6468291ca18d (I added some mods afterwards to make finding the enemies easier)

My method of testing was: 1. start the game, 2. land on experimentation, 3. go inside, 4. look at the console until it said that an earth leviathan got added, 5. if the power limit was reached before that, quit and go to 1, otherwise, 6. try to find the earth leviathan.

I have also seen it add eyeless dogs but didn't manage to find them.

**Comment by BananaPuncher714** [comment]
Thanks for this report! It seems like when I was recoding the configuration for the enemies, the daytime and outside enemies got added to the inside enemies list.

Instead of having to wait around for leviathans to spawn inside, you can change the spawn amount curve to something like 15, and use the UnityExplorer mod to enter freecam and visually confirm the position of any enemies.
