### ISSUE TITLE
Scrap Generation Issue

### ISSUE THREAD

**Issue by VioletXe** [BananaPuncher714/LethalQuantities#46]
I was experimenting with thematic scrap generation based on interiors and encountered a bug which stops the level from loading if certain scraps are used. Initially I only tested this on Infernis with plans to try it on Atlas Abyss and Starlancer's Auralis, however on a whim I tried the same scraps on Titan and got the same error. I haven't tried everything yet, as I only made it halfway through my scrap catalog, but at least these items don't generate.
![Screenshot 2024-01-30 220944](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/c4f13aaa-f281-4245-8c63-7d979aebb2a3)
This is a picture of what happens on Infernis, it's consistant across all the planets I've tried.
![Screenshot 2024-01-31 151046](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/2b30fd48-1d92-4d8e-a501-025ca1f351f6)
The confusing thing about this is that I CAN set their values to 0 to prevent their spawning, but I can't increase it. If any scraps generate via Quantities influence the game refuses to load... but they WILL load if I don't even bother altering the values all together.
![20240130220930_1](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/9201ba7f-aa49-4cd9-b4d1-314b3ec97bc6)
I'm pretty sure this is a quantities bug? Still sort of new to figuring out what causes what.

**Comment by BananaPuncher714** [comment]
This does seem to potentially be a bug with LethalQuantities. Do you have a profile code that I can use to debug further?

**Comment by VioletXe** [comment]
018d6229-0718-2a1c-8f99-285371eabe06
It's a bit packed, sorry.

**Comment by BananaPuncher714** [comment]
This is an issue with LethalLevelLoader and the incomplete items it introduces. The items have a valid spawn prefab, but are missing other important elements. When LethalQuantities fetches all the items at the start of the game, it cannot distinguish between the fake and the real items, so sometimes it gets the fake items and when the game attempts to spawn it, there are errors. I'll look into this, but there is only so much I can do since there is no way to figure out which item is real or not.

**Comment by BananaPuncher714** [comment]
I was not able to get the glizzy from LethalThings to cause an error on Infernis. I set the rarity extremely high(999999), and it seemed fine.
