### ISSUE TITLE
LLL price desync

### ISSUE THREAD

**Issue by VioletXe** [BananaPuncher714/LethalQuantities#56]
Prior to LLL's update the prices worked fine, however for some reason the prices of any moon I set through LQ gets overwritten to A-13's value of 1200. Atlas Abyss has its own price in the configs so it sticks true to that one, but the rest are borked. Any chance this could get fixed in the next couple of days?

**Comment by BananaPuncher714** [comment]
Yes, I noticed this bug too when I was testing. I'll try to get it fixed before the weekend.

**Comment by BananaPuncher714** [comment]
Which version of LethalQuantities and LLL is this with, and what mods do you have enabled? Some LLL moons may not show up with the correct price immediately, but if you change moons to another one the prices should be correct. Do you have a profile code I can test with? The one I was previously using had the bug due to incorrectly named moons.

**Comment by VioletXe** [comment]
Sorry, just woke up. LLL1.1.X all had price malfunctions went I went to bed, but 1.0.7 still works just fine. I'll send a code in a min.

**Comment by BananaPuncher714** [comment]
It is an issue with the moons being loaded by LLL have their ids changed because moons added in by LECore take the same values. I'll add in a quick fix for this, but some default prices in the config might be wrong.
